import { StyleSheet } from 'react-native';

export const recipeCreateStyles = StyleSheet.create({
  backdrop: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(0, 0, 0, 0.72)',
  },
  ctaButton: {
    alignItems: 'center',
    borderRadius: 18,
    flexDirection: 'row',
    gap: 10,
    justifyContent: 'center',
    minHeight: 62,
  },
  ctaButtonDisabled: {
    opacity: 0.45,
  },
  ctaText: {
    color: '#ffffff',
    fontSize: 18,
    fontWeight: '900',
    letterSpacing: 0,
  },
  footer: {
    paddingHorizontal: 20,
    paddingTop: 16,
  },
  goalCard: {
    aspectRatio: 0.78,
    borderRadius: 18,
    justifyContent: 'flex-end',
    overflow: 'hidden',
  },
  goalCardActive: {
    borderColor: '#ff9568',
    borderWidth: 2,
    shadowColor: '#ff9568',
    shadowOffset: { height: 8, width: 0 },
    shadowOpacity: 0.23,
    shadowRadius: 16,
  },
  goalCardPressable: {
    flexBasis: '31.6%',
  },
  goalCheck: {
    alignItems: 'center',
    backgroundColor: '#ff9568',
    borderRadius: 999,
    height: 38,
    justifyContent: 'center',
    position: 'absolute',
    right: -4,
    top: -4,
    width: 38,
    zIndex: 2,
  },
  goalCopy: {
    alignItems: 'center',
    gap: 6,
    paddingBottom: 14,
    paddingHorizontal: 8,
    zIndex: 1,
  },
  goalGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    paddingBottom: 8,
  },
  goalImage: {
    borderRadius: 18,
  },
  goalLabel: {
    color: '#ffffff',
    fontSize: 14,
    fontWeight: '900',
    letterSpacing: 0,
    lineHeight: 18,
    textAlign: 'center',
  },
  handle: {
    alignSelf: 'center',
    backgroundColor: '#d7dbe3',
    borderRadius: 999,
    height: 5,
    marginTop: 16,
    width: 58,
  },
  header: {
    alignItems: 'center',
    flexDirection: 'row',
    minHeight: 52,
    paddingHorizontal: 24,
  },
  modeInputSpacer: {
    height: 22,
  },
  inputErrorText: {
    color: '#e5484d',
    fontSize: 13,
    fontWeight: '700',
    letterSpacing: 0,
    lineHeight: 18,
    marginTop: 8,
  },
  modeTab: {
    alignItems: 'center',
    borderColor: '#e4e8f0',
    borderRadius: 20,
    borderWidth: 1,
    flex: 1,
    flexDirection: 'row',
    gap: 8,
    justifyContent: 'center',
    minHeight: 48,
    paddingHorizontal: 10,
    position: 'relative',
  },
  modeTabActive: {
    backgroundColor: '#fff1eb',
    borderColor: '#fff1eb',
  },
  modeTabText: {
    color: '#64748b',
    flexShrink: 1,
    fontSize: 14,
    fontWeight: '900',
    letterSpacing: 0,
  },
  modeTabTextActive: {
    color: '#05070d',
  },
  modeTabs: {
    flexDirection: 'row',
    gap: 14,
    marginTop: 28,
  },
  nicheCheck: {
    position: 'absolute',
    right: 8,
    top: 8,
  },
  nicheGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 12,
  },
  nicheLabel: {
    color: '#05070d',
    fontSize: 14,
    fontWeight: '900',
    letterSpacing: 0,
    lineHeight: 18,
    textAlign: 'center',
  },
  nicheLabelActive: {
    color: '#ff9568',
  },
  nicheOption: {
    alignItems: 'center',
    borderColor: '#e4e8f0',
    borderRadius: 24,
    borderWidth: 1,
    flexBasis: '30.8%',
    gap: 8,
    justifyContent: 'center',
    minHeight: 92,
    paddingHorizontal: 8,
    paddingVertical: 10,
    position: 'relative',
  },
  nicheOptionActive: {
    borderColor: '#ff9568',
    borderWidth: 1.5,
    shadowColor: '#ff9568',
    shadowOffset: { height: 5, width: 0 },
    shadowOpacity: 0.12,
    shadowRadius: 10,
  },
  otherInput: {
    color: '#111827',
    flex: 1,
    fontSize: 16,
    fontWeight: '800',
    minWidth: 0,
    paddingVertical: 0,
  },
  otherInputRow: {
    alignItems: 'center',
    borderColor: '#ffd8c8',
    borderRadius: 20,
    borderWidth: 1.5,
    flexDirection: 'row',
    gap: 12,
    marginTop: 14,
    minHeight: 54,
    paddingHorizontal: 16,
  },
  overlay: {
    backgroundColor: 'transparent',
    flex: 1,
    justifyContent: 'flex-end',
  },
  primaryButtonPressable: {
    borderRadius: 18,
    overflow: 'hidden',
  },
  proBadge: {
    backgroundColor: '#111827',
    borderRadius: 999,
    paddingHorizontal: 7,
    paddingVertical: 3,
    position: 'absolute',
    right: 5,
    top: 4,
  },
  proBadgeText: {
    color: '#ffffff',
    fontSize: 8,
    fontWeight: '900',
    letterSpacing: 0.4,
    textTransform: 'uppercase',
  },
  questionTitle: {
    color: '#05070d',
    fontSize: 17,
    fontWeight: '900',
    letterSpacing: 0,
    marginBottom: 14,
    marginTop: 32,
  },
  scrollContent: {
    paddingBottom: 118,
    paddingHorizontal: 20,
  },
  sheet: {
    alignSelf: 'center',
    backgroundColor: '#ffffff',
    borderTopLeftRadius: 32,
    borderTopRightRadius: 32,
    overflow: 'hidden',
    width: '100%',
  },
  sheetMotion: {
    width: '100%',
  },
  title: {
    color: '#05070d',
    fontSize: 28,
    fontWeight: '900',
    letterSpacing: 0,
    lineHeight: 33,
    marginTop: 6,
  },
  underlineInput: {
    color: '#111827',
    flex: 1,
    fontSize: 17,
    fontWeight: '700',
    letterSpacing: 0,
    minWidth: 0,
    paddingVertical: 0,
  },
  underlineInputRow: {
    alignItems: 'center',
    borderBottomColor: '#ff9568',
    borderBottomWidth: 1.5,
    flexDirection: 'row',
    gap: 16,
    marginTop: 34,
    minHeight: 50,
    paddingBottom: 10,
  },
  underlineInputRowError: {
    borderBottomColor: '#e5484d',
  },
});
